export const APP_LOAD = 'APP_LOAD';
export const FETCH_CATALOG_INIT = 'FETCH_CATALOG_INIT';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';
export const FETCH_CATALOG_FAILURE = 'FETCH_CATALOG_FAILURE';

export default { APP_LOAD, FETCH_CATALOG_INIT, FETCH_CATALOG_SUCCESS, FETCH_CATALOG_FAILURE };
